pinocchio: ActuatorDCMotorData< Scalar_ > Class Template Reference
ActuatorDCMotorData< Scalar_ > Class Template Reference
Actuators » Motor models » Linear motor model (second order)
Template for handling data related to a second order linear DC motor model.
#include <actuators/dc-linear-motor-model.hpp>
Public Types
typedef Scalar_ Scalar_t
typedef Eigen::Matrix< Scalar_, 10, 1 > Parameters_t
typedef Eigen::Matrix< Scalar_, 3, 1 > Observations_t
typedef Eigen::Matrix< Scalar_, 6, 1 > S_t
typedef Eigen::Matrix< Scalar_, 2, 1 > X_t
typedef Eigen::Matrix< Scalar_, 2, 1 > dX_t
typedef Eigen::Matrix< Scalar_, 1, 1 > U_t
typedef Eigen::Matrix< Scalar_, 3, 1, 0 > Vector3Scalar
Public Member Functions
const Observations_t & h () const
Return observation vector.
const Parameters_t & c () const
Return parameters.
const S_t & S () const
Returns selection matrix.
Observations_t & h ()
Scalar_ current () const
Scalar_ motorVelocity () const
void rotorInertia (Scalar_ c)
Rotor inertia (kg/m2) - \(B_m \).
void rotorResistor (Scalar_ c)
Rotor resistor (Ohm) - \(R\).
void torqueConst (Scalar_ c)
Torque constant (Nm/A) - \(K_m \).
void speedTorqueGrad (Scalar_ c)
Speed torque gradient (rads^-1/Nm) \(D_m \).
void backEMF (Scalar_ c)
Terminal Inductance (Henry)
void setS (S_t &S)
Public Attributes
Vector3Scalar state
State: current, q, dq.
Vector3Scalar dstate
Derivation of the state.
Scalar_ V
Control: potential.
Scalar_ tau_l
Load torque.
Scalar_ rotorInertia
Rotor inertia (kg/m2)
Scalar_ rotorResistor
Rotor resistor (Ohm)
Scalar_ torqueConst
Torque constant (Nm/A)
Scalar_ speedTorqueGrad
Speed torque gradient (rads^-1/Nm)
Scalar_ terminalInductance
Terminal Inductance (Henry)
Scalar_ backEMF
Back electro magnetic force constant.
Scalar_ gearRatio
Gear ratio.
Scalar_ motor_torque
Internal intermediate variables.
Protected Member Functions
void updateFirstThreeParameters ()
Update the first three parameters of the actuators:
Protected Attributes
Observations_t h_
Observation variables.
Parameters_t c_
Vector parameters.
S_t S_
Selection matrix.
Detailed Description
template<typename Scalar_>
class se3::ActuatorDCMotorData< Scalar_ >
Template for handling data related to a second order linear DC motor model.
Template Parameters
Scalar_ {description}
Definition at line 124 of file dc-linear-motor-model.hpp.
Member Function Documentation
void backEMF (Scalar_ c) inline
Terminal Inductance (Henry)
Back electro magnetic force constant \(K_b \) It is the inverse of the speed torque gradient constant (\(k_N\)) in Maxon datasheet. More exactly the maxon datasheet gives rpm/V. So it is \(\frac{60}{ 2 \pi k_N)}\)
Definition at line 170 of file dc-linear-motor-model.hpp.
References ActuatorDCMotorData< Scalar_ >::c(), ActuatorDCMotorData< Scalar_ >::c_, ActuatorDCMotorData< Scalar_ >::h(), ActuatorDCMotorData< Scalar_ >::h_, ActuatorDCMotorData< Scalar_ >::S(), ActuatorDCMotorData< Scalar_ >::S_, and ActuatorDCMotorData< Scalar_ >::updateFirstThreeParameters().
void rotorInertia (Scalar_ c) inline
Rotor inertia (kg/m2) - \(B_m \).
Internal parameters of the actuator.
Definition at line 146 of file dc-linear-motor-model.hpp.
References ActuatorDCMotorData< Scalar_ >::c(), ActuatorDCMotorData< Scalar_ >::c_, and ActuatorDCMotorData< Scalar_ >::updateFirstThreeParameters().
Member Data Documentation
Scalar_ backEMF
Back electro magnetic force constant.
It is the inverse of the speed constant (k_N) in Maxon datasheet. More exactly the maxon datasheet gives rpm/V. So it is 1/(k_N* 2* /60)
Definition at line 51 of file dc-motor-model.hpp.
Scalar_ motor_torque
Internal intermediate variables.
DCMotor Torque
Definition at line 70 of file dc-motor-model.hpp.
Scalar_ rotorInertia
Rotor inertia (kg/m2)
Internal parameters of the actuator.
Definition at line 38 of file dc-motor-model.hpp.
The documentation for this class was generated from the following files:
dc-linear-motor-model.hpp
dc-motor-model.hpp