pinocchio: ActuatorDCNonLinearMotorModel< Scalar_ > Class Template Reference
ActuatorDCNonLinearMotorModel< Scalar_ > Class Template Reference
Actuators » Motor models » Non linear motor model.
Template implementing a non linear DC motor model.
#include <actuators/dc-non-linear-motor-model.hpp>
Public Member Functions
void ode_func (typename ActuatorDCNonLinearMotorData< Scalar_ >::dX_t &dstate, typename ActuatorDCNonLinearMotorData< Scalar_ >::X_t &state, typename ActuatorDCNonLinearMotorData< Scalar_ >::U_t &control, Force &fext, ActuatorDCNonLinearMotorData< Scalar_ > &data)
void get_force (ActuatorDCNonLinearMotorData< Scalar_ > &data, Force &aForce) const
ActuatorDCNonLinearMotorData< Scalar_ > createData () const
Protected Attributes
std::string name_
Detailed Description
template<typename Scalar_>
class se3::ActuatorDCNonLinearMotorModel< Scalar_ >
Template implementing a non linear DC motor model.
Template Parameters
Scalar_ {description}
Definition at line 232 of file dc-non-linear-motor-model.hpp.
Member Function Documentation
void ode_func (typename ActuatorDCNonLinearMotorData< Scalar_ >::dX_t & dstate, typename ActuatorDCNonLinearMotorData< Scalar_ >::X_t & state, typename ActuatorDCNonLinearMotorData< Scalar_ >::U_t & control, Force & fext, ActuatorDCNonLinearMotorData< Scalar_ > & data) inline
di/dt = (-Ri + V - K_b dtheta/dt)/L
Definition at line 240 of file dc-non-linear-motor-model.hpp.
References ForceBase< Derived >::angular(), ActuatorDCNonLinearMotorData< Scalar_ >::c(), ActuatorDCNonLinearMotorData< Scalar_ >::h(), ForceBase< Derived >::linear(), ActuatorDCNonLinearMotorData< Scalar_ >::S(), and ForceBase< Derived >::toVector().
The documentation for this class was generated from the following file:
dc-non-linear-motor-model.hpp