pinocchio: LieGroupOperationBase< Derived > Struct Template Reference
LieGroupOperationBase< Derived > Struct Template Reference
Public Types
typedef Derived LieGroupDerived
Public Attributes
SE3_LIE_GROUP_TYPEDEF_TEMPLATE
Protected Member Functions
LieGroupOperationBase ()
LieGroupOperationBase (const LieGroupOperationBase &)
API with return value as argument
template<class ConfigIn_t , class Tangent_t , class ConfigOut_t >
static void integrate (const Eigen::MatrixBase< ConfigIn_t > &q, const Eigen::MatrixBase< Tangent_t > &v, const Eigen::MatrixBase< ConfigOut_t > &qout)
Integrate joint's configuration for a tangent vector during one unit time.
template<class ConfigL_t , class ConfigR_t , class ConfigOut_t >
static void interpolate (const Eigen::MatrixBase< ConfigL_t > &q0, const Eigen::MatrixBase< ConfigR_t > &q1, const Scalar &u, const Eigen::MatrixBase< ConfigOut_t > &qout)
Interpolation between two joint's configurations.
template<class Config_t >
static void normalize (const Eigen::MatrixBase< Config_t > &qout)
Normalize the joint configuration given as input. For instance, the quaternion must unitary.
template<class ConfigL_t , class ConfigR_t , class Tangent_t >
static void difference (const Eigen::MatrixBase< ConfigL_t > &q0, const Eigen::MatrixBase< ConfigR_t > &q1, const Eigen::MatrixBase< Tangent_t > &d)
the tangent vector that must be integrated during one unit time to go from q0 to q1
template<class ConfigL_t , class ConfigR_t >
static double squaredDistance (const Eigen::MatrixBase< ConfigL_t > &q0, const Eigen::MatrixBase< ConfigR_t > &q1)
Squared distance between two configurations of the joint.
template<class ConfigL_t , class ConfigR_t >
static double distance (const Eigen::MatrixBase< ConfigL_t > &q0, const Eigen::MatrixBase< ConfigR_t > &q1)
Distance between two configurations of the joint.
template<class ConfigL_t , class ConfigR_t >
static bool isSameConfiguration (const Eigen::MatrixBase< ConfigL_t > &q0, const Eigen::MatrixBase< ConfigR_t > &q1, const Scalar &prec=Eigen::NumTraits< Scalar >::dummy_precision())
Check if two configurations are equivalent within the given precision.
template<class Config_t >
void random (const Eigen::MatrixBase< Config_t > &qout) const
Generate a random joint configuration, normalizing quaternions when necessary.
template<class ConfigL_t , class ConfigR_t , class ConfigOut_t >
void randomConfiguration (const Eigen::MatrixBase< ConfigL_t > &lower_pos_limit, const Eigen::MatrixBase< ConfigR_t > &upper_pos_limit, const Eigen::MatrixBase< ConfigOut_t > &qout) const
Generate a configuration vector uniformly sampled among provided limits.
API that allocates memory
template<class Config_t , class Tangent_t >
static ConfigVector_t integrate (const Eigen::MatrixBase< Config_t > &q, const Eigen::MatrixBase< Tangent_t > &v)
template<class ConfigL_t , class ConfigR_t >
static ConfigVector_t interpolate (const Eigen::MatrixBase< ConfigL_t > &q0, const Eigen::MatrixBase< ConfigR_t > &q1, const Scalar &u)
template<class ConfigL_t , class ConfigR_t >
static TangentVector_t difference (const Eigen::MatrixBase< ConfigL_t > &q0, const Eigen::MatrixBase< ConfigR_t > &q1)
ConfigVector_t random () const
template<class ConfigL_t , class ConfigR_t >
ConfigVector_t randomConfiguration (const Eigen::MatrixBase< ConfigL_t > &lower_pos_limit, const Eigen::MatrixBase< ConfigR_t > &upper_pos_limit) const
Default implementations
template<class ConfigL_t , class ConfigR_t , class ConfigOut_t >
static void interpolate_impl (const Eigen::MatrixBase< ConfigL_t > &q0, const Eigen::MatrixBase< ConfigR_t > &q1, const Scalar &u, const Eigen::MatrixBase< ConfigOut_t > &qout)
template<class Config_t >
static void normalize_impl (const Eigen::MatrixBase< Config_t > &qout)
template<class ConfigL_t , class ConfigR_t >
static double squaredDistance_impl (const Eigen::MatrixBase< ConfigL_t > &q0, const Eigen::MatrixBase< ConfigR_t > &q1)
template<class ConfigL_t , class ConfigR_t >
static bool isSameConfiguration_impl (const Eigen::MatrixBase< ConfigL_t > &q0, const Eigen::MatrixBase< ConfigR_t > &q1, const Scalar &prec)
Index nq () const
Index nv () const
Get dimension of Lie Group tangent space.
ConfigVector_t neutral () const
Get neutral element as a vector.
std::string name () const
Get name of instance.
Derived & derived ()
const Derived & derived () const
Detailed Description
template<typename Derived>
struct se3::LieGroupOperationBase< Derived >
Definition at line 86 of file operation-base.hpp.
Constructor & Destructor Documentation
LieGroupOperationBase () inline protected
Default constructor.
Prevent the construction of derived class.
Definition at line 278 of file operation-base.hpp.
LieGroupOperationBase (const LieGroupOperationBase< Derived > &) inline protected
Copy constructor
Prevent the copy of derived class.
Definition at line 283 of file operation-base.hpp.
Member Function Documentation
void difference (const Eigen::MatrixBase< ConfigL_t > & q0, const Eigen::MatrixBase< ConfigR_t > & q1, const Eigen::MatrixBase< Tangent_t > & d) static
the tangent vector that must be integrated during one unit time to go from q0 to q1
Parameters
[in] q0 Initial configuration
[in] q1 Wished configuration
Returns
The corresponding velocity
Definition at line 105 of file operation-base.hxx.
Referenced by LieGroupOperationBase< Derived >::isSameConfiguration().
double distance (const Eigen::MatrixBase< ConfigL_t > & q0, const Eigen::MatrixBase< ConfigR_t > & q1) static
Distance between two configurations of the joint.
Parameters
[in] q0 Configuration 1
[in] q1 Configuration 2
Returns
The corresponding distance
Definition at line 129 of file operation-base.hxx.
void integrate (const Eigen::MatrixBase< ConfigIn_t > & q, const Eigen::MatrixBase< Tangent_t > & v, const Eigen::MatrixBase< ConfigOut_t > & qout) static
Integrate joint's configuration for a tangent vector during one unit time.
Parameters
[in] q initatial configuration (size full model.nq)
[in] v joint velocity (size full model.nv)
Returns
The configuration integrated
Definition at line 29 of file operation-base.hxx.
Referenced by LieGroupOperationBase< Derived >::isSameConfiguration().
void interpolate (const Eigen::MatrixBase< ConfigL_t > & q0, const Eigen::MatrixBase< ConfigR_t > & q1, const Scalar & u, const Eigen::MatrixBase< ConfigOut_t > & qout) static
Interpolation between two joint's configurations.
Parameters
[in] q0 Initial configuration to interpolate
[in] q1 Final configuration to interpolate
[in] u u in [0;1] position along the interpolation.
Returns
The interpolated configuration (q0 if u = 0, q1 if u = 1)
Definition at line 52 of file operation-base.hxx.
References LieGroupOperationBase< Derived >::normalize().
Referenced by LieGroupOperationBase< Derived >::isSameConfiguration().
bool isSameConfiguration (const Eigen::MatrixBase< ConfigL_t > & q0, const Eigen::MatrixBase< ConfigR_t > & q1, const Scalar & prec = Eigen::NumTraits<Scalar>::dummy_precision()) static
Check if two configurations are equivalent within the given precision.
Parameters
[in] q0 Configuration 0
[in] q1 Configuration 1
Definition at line 138 of file operation-base.hxx.
References LieGroupOperationBase< Derived >::difference(), LieGroupOperationBase< Derived >::integrate(), LieGroupOperationBase< Derived >::interpolate(), and LieGroupOperationBase< Derived >::randomConfiguration().
void normalize (const Eigen::MatrixBase< Config_t > & qout) static
Normalize the joint configuration given as input. For instance, the quaternion must unitary.
Returns
The normalized joint configuration.
Definition at line 67 of file operation-base.hxx.
Referenced by LieGroupOperationBase< Derived >::interpolate().
LieGroupOperationBase< Derived >::Index nq () const
Get dimension of Lie Group vector representation
For instance, for SO(3), the dimension of the vector representation is 4 (quaternion) while the dimension of the tangent space is 3.
Definition at line 243 of file operation-base.hxx.
void random (const Eigen::MatrixBase< Config_t > & qout) const
Generate a random joint configuration, normalizing quaternions when necessary.
Warning
Do not take into account the joint limits. To shoot a configuration uniformingly depending on joint limits, see uniformySample
Returns
The joint configuration
Warning
Do not take into account the joint limits. To shoot a configuration uniformingly depending on joint limits, see randomConfiguration
Returns
The joint configuration
Definition at line 84 of file operation-base.hxx.
void randomConfiguration (const Eigen::MatrixBase< ConfigL_t > & lower_pos_limit, const Eigen::MatrixBase< ConfigR_t > & upper_pos_limit, const Eigen::MatrixBase< ConfigOut_t > & qout) const
Generate a configuration vector uniformly sampled among provided limits.
Parameters
[in] lower_pos_limit lower joint limit
[in] upper_pos_limit upper joint limit
Returns
The joint configuration
Definition at line 92 of file operation-base.hxx.
Referenced by LieGroupOperationBase< Derived >::isSameConfiguration().
double squaredDistance (const Eigen::MatrixBase< ConfigL_t > & q0, const Eigen::MatrixBase< ConfigR_t > & q1) static
Squared distance between two configurations of the joint.
Parameters
[in] q0 Configuration 1
[in] q1 Configuration 2
Returns
The corresponding distance
Definition at line 118 of file operation-base.hxx.
The documentation for this struct was generated from the following files:
operation-base.hpp
operation-base.hxx